import Head from 'next/head'
import Image from 'next/image'
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  useQuery,
  gql
} from "@apollo/client";
import parse from 'html-react-parser';
import styles from '../styles/Home.module.css'


export default function Home({ posts }) {

  console.log('post:',posts);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>

          {posts.map(post=>{
            return <a key={post.title} className={styles.card}>
            <h2>{post.title}</h2>
            <p>{parse(post.content)}</p>
          </a>
          })}

        </div>

      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export async function getStaticProps(){

  const client = new ApolloClient({
    uri: 'http://18.233.165.89/graphql',
    cache: new InMemoryCache()
  });

  const response = await client.query({
    query: gql`
      query MyQuery {
        posts {
          edges {
            node {
              uri
              title
              content
            }
          }
        }
      }
    `
  });
  
  var posts = response.data.posts.edges.map(({node})=>node);

  return {  
    props:{
      posts
    }
  }

}